# Factorización LU

In [1]:
Threads.nthreads() # Obtenemos el numero de hilos disponibles en el proceso

4

## Factorización LU secuencial con algoritmo de Crout

In [3]:
using LinearAlgebra
function LU(A::Matrix{Float64})
    m,n = size(A)
    U = Matrix{Float64}(I, n, n)
    L = copy(A)
    for i = 1:n
        for j = i+1:n
            U[i,j] = L[i,j]/L[i,i]
            L[i:end,j] = L[i:end,j] - U[i,j]*L[i:end,i]
        end
    end
    return L,U
end

LU (generic function with 1 method)

### Ejemplo matriz 4x4 simple

In [19]:
A1 = rand(1000,1000)

1000×1000 Matrix{Float64}:
 0.531245   0.840443   0.324613   …  0.231392   0.429289   0.740698
 0.199012   0.804679   0.194388      0.781432   0.406935   0.478237
 0.364188   0.414361   0.768961      0.517587   0.801675   0.377513
 0.994625   0.176044   0.502354      0.187411   0.764038   0.115481
 0.314001   0.511661   0.131091      0.176075   0.869293   0.750911
 0.978091   0.27864    0.388003   …  0.192211   0.992112   0.59318
 0.406506   0.248327   0.889899      0.133758   0.659295   0.318746
 0.585159   0.460981   0.0227243     0.508858   0.139703   0.856802
 0.104612   0.0131676  0.543797      0.314539   0.558658   0.961856
 0.604983   0.883581   0.937919      0.0600933  0.981399   0.148655
 0.342449   0.212408   0.985459   …  0.646976   0.233151   0.965976
 0.799217   0.117264   0.0777435     0.417677   0.399047   0.401566
 0.402942   0.234303   0.338502      0.859909   0.0388994  0.964968
 ⋮                                ⋱                        
 0.628572   0.322654   0.77347

In [20]:
L,U = LU(A1)
open("LUserial.txt","w") do io
    println(io,"A =", A1)
    println(io,"L=",L)
    println(io,"U=",U)
end
println("Tiempo de Ejecucion: ",@time LU(A1))

  4.588439 seconds (2.00 M allocations: 10.235 GiB, 12.88% gc time)
Tiempo de Ejecucion: ([0.5312445262029812 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 -5.551115123125783e-17 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 -1.1102230246251565e-16 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.1102230246251565e-16 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 5.551115123125783e-17 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 -1.1102230246251565e-16 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 -5.551115123125783e-17 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0

Excessive output truncated after 524291 bytes.

0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 5.551115123125783e-17 4.440892098500626e-16 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 8.881784197001252e-16 -2.220446049250313e-16 -4.440892098500626e-16 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.1102230246251565e-16 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0

LoadError: InterruptException:

## Factorización LU paralelo

In [75]:
Threads.threadid() # nos da el numero de hilo actual de execucion 

1

In [21]:
using LinearAlgebra
using Base.Threads

function parallel_LU(A::Matrix{Float64})
    m,n = size(A)
    U = Matrix{Float64}(I, n, n)
    L = copy(A)
    num_threads = Threads.nthreads() # Obtenemos el numero de hilos disponibles en el proceso
    threads = []
    for i = 1:n-1
        for j = i+1:n
            if length(threads) < num_threads
                # Creamos una tarea en el hilo actual, en este caso  la tarea
                # es hacer: L[i,j] = U[i,j]/U[j,j] y U[i,j:end] -= L[i,j]*U[j,j:end]
                push!(threads, Threads.@spawn begin
                    U[i,j] = L[i,j]/L[i,i]
                    L[i:end,j] = L[i:end,j] - U[i,j]*L[i:end,i]
                end)
            else # Cuando ya tengamos en ejecucion los 4 hilos
                wait(threads[1]) # Esperamos a que la tarea 1 iniciada acabe
                # La tarea 1 acabo y asi lo podemos eliminar
                popfirst!(threads) # Elimina el primer elemento de la lista
                                   # threads; es decir, la primera tarea
            end
        end
    end
    for thread in threads # Recorre las tareas, una en cada hilo
        # Esperamos a que acaben de ejecutarse todos los hilos para finalizar la ejecucion
        wait(thread) 
    end
    return L,U
end

parallel_LU (generic function with 1 method)

### Ejemplo matriz 4x4 simple

### Pruebas


In [22]:
# misma matrizA1 de orden 1000
L,U = parallel_LU(A1)
open("LUparalelo.txt","w") do io
    println(io,"L=",L)
    println(io,"U=",U)
end
println("Tiempo de Ejecucion: ",@time parallel_LU(A1))

  2.862505 seconds (2.45 M allocations: 5.276 GiB, 17.43% gc time)
Tiempo de Ejecucion: ([0.5312445262029812 0.0 0.0 0.0 0.0 0.7888655029358267 0.0 0.7420950211252872 0.0 0.8640249894556998 0.0 0.5293833145840889 0.0 0.0027319336560808205 0.0 0.35818475868259936 0.0 0.3513952234484925 0.0 0.44455090604345504 0.0 0.33420786885252796 0.0 0.7932976786256317 -1.1102230246251565e-16 0.921368110112549 0.0 0.7308288908320628 0.0 0.06585363328085436 0.0 0.48669411338991153 0.0 0.50923573343181 0.0 0.5974256015182012 0.0 0.9798505840846334 0.0 0.24770041343597615 0.0 0.3320463326055645 0.0 0.14638468062779897 0.0 0.8556114695798496 0.0 0.5185352297064301 1.1102230246251565e-16 0.29644657814538944 0.0 0.18085409934746188 0.0 0.07653265003702425 0.0 0.9930716002897829 0.0 0.2292287004372452 0.0 0.18280747195816105 0.0 0.13157624023512127 0.0 0.5727067634948028 0.0 0.3329245171333801 0.0 0.46767626287366193 0.0 0.1910285891286888 0.0 0.48190840036679483 0.0 0.26741223888310905 0.0 0.09666371223004

Excessive output truncated after 524290 bytes.

 0.0 -0.9733966154018631 0.0 0.5995766883952214 0.0 0.6041963255027357 -1.3877787807814457e-17 0.5367925270660798 0.0 -0.6232272260238314 0.0 -0.5970390960552517 0.0 0.33228374239079284 0.0 0.37036293396414766 0.0 1.0780569743459076 0.0 0.36778501766425653 0.0 0.17396169924275712 0.0 -0.08782680743229095 0.0 -0.3007847656323027 0.0 0.21591331775239514 0.0 -0.7120555612326783 0.0 0.7806913515595645 0.0 0.09281499555549638 -1.1102230246251565e-16 0.023281700814495213 0.0 0.867097558091328 0.0 0.27478397964109136 -1.1102230246251565e-16 -0.9466900319044583 0.0 -0.2912571470098688 -1.1102230246251565e-16 0.5431292111191104 0.0 0.6044613096053459 0.0 -0.06732683749839952 0.0 -0.048353809570098466 0.0 -0.016159636431210704 0.0 0.45484494882484106 0.0 1.4174933588807355 0.0 -0.29051795702730354 0.0 -0.3853820154304795 0.0 1.5761963051221435 0.0 -0.6919121197986208 -2.7755575615628914e-17 -0.6246550461749998 0.0 0.4644752347791975 0.0 -0.6036471725623686 0.0 0.5006291536548 0.0 0.8318329110320

LoadError: InterruptException:

In [118]:
A2 = rand(1000,1000)
@time LU(A2)

  7.020190 seconds (2.00 M allocations: 10.235 GiB, 18.10% gc time)


([0.8452821195282225 0.0 … -5.551115123125783e-17 0.0; 0.9160560317046536 0.17985812817615307 … 0.0 0.0; … ; 0.536559081949998 0.10813617180393381 … -300.5426109861468 0.0; 0.16504292942979737 0.26166025584390745 … -444.84722416106825 -25.200020374631094], [1.0 0.26620899055574165 … 0.5755909387878158 0.769901336621542; 0.0 1.0 … -2.0783222486230293 1.6362865456780171; … ; 0.0 0.0 … 1.0 2.5033157547066778; 0.0 0.0 … 0.0 1.0])

In [119]:
L,U = LU(A2)
display(L)
display(U)

1000×1000 Matrix{Float64}:
 0.845282    0.0          0.0       …    -5.55112e-17    0.0
 0.916056    0.179858     0.0             0.0            0.0
 0.115166    0.235603    -0.281996        0.0            6.93889e-18
 0.106053    0.729591    -2.31229         0.0            0.0
 0.159844    0.668628    -1.64607         0.0            0.0
 0.0787302   0.158768    -0.29343   …     0.0            0.0
 0.102352   -0.00447919   0.91425         0.0            0.0
 0.306607    0.630853    -1.42596         0.0            0.0
 0.205708    0.352664    -0.1909          0.0           -5.55112e-17
 0.749222   -0.0604807    0.161594        0.0           -2.77556e-17
 0.0288268   0.0754197    0.23      …     5.55112e-17    0.0
 0.665315    0.503521    -1.32246         0.0            0.0
 0.781078    0.426975    -0.88416         0.0            0.0
 ⋮                                  ⋱                  
 0.390871    0.79246     -2.23842         0.0            0.0
 0.856593    0.341605    -0.464248     

1000×1000 Matrix{Float64}:
 1.0  0.266209  0.111986   0.938497  …   0.259003    0.575591     0.769901
 0.0  1.0       3.20991   -2.34085       2.84327    -2.07832      1.63629
 0.0  0.0       1.0       -2.58047       0.206498   -1.938       -0.215002
 0.0  0.0       0.0        1.0           0.373736    0.554051     0.247023
 0.0  0.0       0.0        0.0           0.229988    0.697252     1.03649
 0.0  0.0       0.0        0.0       …  -0.106837    1.37887      1.84683
 0.0  0.0       0.0        0.0          -2.53058    -1.36554     -1.59397
 0.0  0.0       0.0        0.0           0.93107     0.628196     0.725573
 0.0  0.0       0.0        0.0           0.045685    0.10619      0.535842
 0.0  0.0       0.0        0.0           7.37326     6.81458     -8.24359
 0.0  0.0       0.0        0.0       …   0.283041   -0.387373     0.372731
 0.0  0.0       0.0        0.0          -3.55424    -0.119619     0.164972
 0.0  0.0       0.0        0.0          -0.801498   -0.0542482    0.0339931
 ⋮

In [120]:
@time parallel_LU(A2)

  2.831837 seconds (2.45 M allocations: 5.276 GiB, 17.15% gc time)


([0.8452821195282225 0.0 … -5.551115123125783e-17 0.6507838336470686; 0.9160560317046536 0.17985812817615307 … 0.0 0.99957219849511; … ; 0.536559081949998 0.10813617180393381 … -110.85159773326941 0.03192776357119875; 0.16504292942979737 0.26166025584390745 … -34.75674800429874 -0.0474546595983556], [1.0 0.26620899055574165 … 0.5755909387878158 0.0; 0.0 1.0 … -2.0783222486230293 0.0; … ; 0.0 0.0 … 1.0 0.10582099569759225; 0.0 0.0 … 0.0 1.0])

## Factorización LU por bloques 

In [23]:
using LinearAlgebra

function is_singular(A)
    return det(A) == 0
end

function block_LU(A)
    n = size(A, 1) # Numero de filas, debe ser par
    if n == 1
        return A, A, A
    end
    # Dividimos a la matriz en bloques de (n/2)*(n/2) para factorzarlo como sigue
    #     [ A_11 | A_12 ]    [ L_11 |  0  ] [ U_11 | U_12 ]
    # A = | ----------- | =  ¡ ---------- ] [ ----------- ]
    #     [ A_21 | A_22 ]    [ L_21 | L22 ] [  0   | U_22 ]
    
    m = n ÷ 2
    A11 = A[1:m, 1:m]
    A12 = A[1:m, m+1:end]
    A21 = A[m+1:end, 1:m]
    A22 = A[m+1:end, m+1:end]

    if is_singular(A11) || is_singular(A22)
        error("La matriz es singular")
    end

    # Efectuar el algoritmo de Crout como si tuvieramos una matriz 2x2
    L11, U11 = impLU(A11)
    U12 = L11 \ A12
    L21 = A21 / U11
    L22, U22 = impLU(A22 - L21*U12)

    # Formacion de matrices L, U por bloques tambien
    L = [L11 zeros(m, n-m); 
         L21 L22]
    U = [U11 U12; 
         zeros(n-m, m) U22]

    return L, U
end

# Algoritmo Crout
function impLU(A::Matrix{Float64})
    m,n = size(A)
    U = Matrix{Float64}(I, n, n)
    L = copy(A)
    for i = 1:n-1
        for j = i+1:n
            U[i,j] = L[i,j]/L[i,i]
            L[i:end,j] = L[i:end,j] - U[i,j]*L[i:end,i]
        end
    end
    return L,U
end

impLU (generic function with 1 method)

### Pruebas

In [24]:
# misma matriz
L,U = block_LU(A1)
open("LUbloqueserial.txt","w") do io
    println(io,"L=",L)
    println(io,"U=",U)
end
println("Tiempo de Ejecucion: ",@time block_LU(A1))

  0.961884 seconds (998.04 k allocations: 2.668 GiB, 18.27% gc time)
Tiempo de Ejecucion: ([0.5312445262029812 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 -5.551115123125783e-17 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 -1.1102230246251565e-16 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.1102230246251565e-16 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 5.551115123125783e-17 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 -1.1102230246251565e-16 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 -5.551115123125783e-17 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.

Excessive output truncated after 524290 bytes.

0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0

LoadError: InterruptException:

In [126]:
@time block_LU(A2)

  2.286106 seconds (2.68 M allocations: 2.778 GiB, 10.58% gc time, 57.84% compilation time)


([0.8452821195282225 0.0 … 0.0 0.0; 0.9160560317046536 0.17985812817615307 … 0.0 0.0; … ; 0.536559081949998 0.10813617180393381 … -300.54250632266786 0.0; 0.16504292942979737 0.26166025584390745 … -444.8470667464257 -25.200020276243777], [1.0 0.26620899055574165 … 0.5755909387973873 0.7699013366153409; 0.0 1.0 … -2.078322248675245 1.636286544947917; … ; 0.0 0.0 … 1.0 2.5033157389420113; 0.0 0.0 … 0.0 1.0])

In [127]:
L, U = block_LU(A2)

([0.8452821195282225 0.0 … 0.0 0.0; 0.9160560317046536 0.17985812817615307 … 0.0 0.0; … ; 0.536559081949998 0.10813617180393381 … -300.54250632266786 0.0; 0.16504292942979737 0.26166025584390745 … -444.8470667464257 -25.200020276243777], [1.0 0.26620899055574165 … 0.5755909387973873 0.7699013366153409; 0.0 1.0 … -2.078322248675245 1.636286544947917; … ; 0.0 0.0 … 1.0 2.5033157389420113; 0.0 0.0 … 0.0 1.0])

## Factorización LU por bloques con LU paralelo

In [25]:
using Base.Threads
using LinearAlgebra

function is_singular(A)
    return det(A) == 0
end

function pseudo_parallel_LU_block_LU(A)
    n = size(A, 1)
    if n == 1
        return A, A, A
    end

    m = n ÷ 2
    A11 = A[1:m, 1:m]
    A12 = A[1:m, m+1:end]
    A21 = A[m+1:end, 1:m]
    A22 = A[m+1:end, m+1:end]

    if is_singular(A11) || is_singular(A22)
        error("La matriz es singular")
    end

    L11, U11 = parallel_LU(A11)
    U12 = L11 \ A12
    L21 = A21 / U11
    L22, U22 = parallel_LU(A22 - L21*U12)

    L = [L11 zeros(m, n-m); 
         L21 L22]
    U = [U11 U12; 
         zeros(n-m, m) U22]

    return L, U
end

function parallel_LU(A::Matrix{Float64})
    m,n = size(A)
    U = Matrix{Float64}(I, n, n)
    L = copy(A)
    num_threads = Threads.nthreads()
    threads = []
    for i = 1:n-1
        for j = i+1:n
            if length(threads) < num_threads
                push!(threads, Threads.@spawn begin
                    U[i,j] = L[i,j]/L[i,i]
                    L[i:end,j] = L[i:end,j] - U[i,j]*L[i:end,i]
                end)
            else
                wait(threads[1])
                popfirst!(threads)
            end
        end
    end
    for thread in threads
        wait(thread)
    end
    return L,U
end

parallel_LU (generic function with 1 method)

### Pruebas

In [26]:
# misma matriz
L,U = pseudo_parallel_LU_block_LU(A1)
open("LUbloqueparalelo.txt","w") do io
    println(io,"A =", A1)
    println(io,"L=",L)
    println(io,"U=",U)
end
println("Tiempo de Ejecucion: ",@time pseudo_parallel_LU_block_LU(A1))

  0.784273 seconds (1.22 M allocations: 1.434 GiB, 17.37% gc time)
Tiempo de Ejecucion: ([0.5312445262029812 0.0 0.0 0.0 0.0 0.7888655029358267 0.0 0.7420950211252872 0.0 0.8640249894556998 0.0 0.5293833145840889 0.0 0.0027319336560808205 0.0 0.35818475868259936 0.0 0.3513952234484925 0.0 0.44455090604345504 0.0 0.33420786885252796 0.0 0.7932976786256317 -1.1102230246251565e-16 0.921368110112549 0.0 0.7308288908320628 0.0 0.06585363328085436 0.0 0.48669411338991153 0.0 0.50923573343181 0.0 0.5974256015182012 0.0 0.9798505840846334 0.0 0.24770041343597615 0.0 0.3320463326055645 0.0 0.14638468062779897 0.0 0.8556114695798496 0.0 0.5185352297064301 1.1102230246251565e-16 0.29644657814538944 0.0 0.18085409934746188 0.0 0.07653265003702425 0.0 0.9930716002897829 0.0 0.2292287004372452 0.0 0.18280747195816105 0.0 0.13157624023512127 0.0 0.5727067634948028 0.0 0.3329245171333801 0.0 0.46767626287366193 0.0 0.1910285891286888 0.0 0.48190840036679483 0.0 0.26741223888310905 0.0 0.09666371223004

Excessive output truncated after 524289 bytes.

 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0

LoadError: InterruptException:

In [4]:
@time pseudo_parallel_LU_block_LU(A2)

LoadError: UndefVarError: `A2` not defined

In [102]:
A3 = rand(2000,2000)

2000×2000 Matrix{Float64}:
 0.0549109  0.0202591  0.51384    …  0.818147   0.683864   0.809701
 0.170037   0.913431   0.684139      0.862794   0.983926   0.55613
 0.704906   0.655008   0.56884       0.776266   0.254161   0.298475
 0.0554005  0.315595   0.71282       0.0627926  0.163593   0.809113
 0.704343   0.076775   0.776898      0.20593    0.517136   0.336386
 0.298656   0.450285   0.392252   …  0.384504   0.202468   0.889039
 0.876766   0.102646   0.661861      0.327693   0.331203   0.364921
 0.942986   0.304658   0.91167       0.847318   0.904285   0.432371
 0.227969   0.259491   0.0670966     0.86364    0.284437   0.199149
 0.825595   0.687794   0.54205       0.249374   0.830727   0.969441
 0.772652   0.450444   0.94256    …  0.407625   0.727248   0.183077
 0.755856   0.31815    0.211984      0.468109   0.845889   0.0877412
 0.0261066  0.405011   0.83543       0.997032   0.0891597  0.618466
 ⋮                                ⋱                        
 0.571677   0.28162    0.8710

In [108]:
@time LU(A3)

 55.049873 seconds (8.00 M allocations: 80.690 GiB, 9.71% gc time)


([1.0 0.0 … 0.0 0.0; 3.0965922842084077 1.0 … 0.0 0.0; … ; 15.209444148889675 0.39577317022402086 … 1.0 0.0; 7.13470924973447 0.00209883896903328 … -5.269290414079614 1.0], [0.054910881633198905 0.02025913121896805 … 0.6838641259466856 0.809700851562404; 0.0 0.8506970735473804 … -1.1337227773796799 -1.9511837272862618; … ; 0.0 0.0 … 3.9673600769847734 5.929271422913388; 0.0 2.168404344971009e-19 … 0.0 24.413557992267275])

In [109]:
@time parallel_LU(A3)

 26.141261 seconds (10.10 M allocations: 40.988 GiB, 11.66% gc time)


([1.0 0.0 … 0.0 0.0; 3.0965922842084077 1.0 … 0.0 0.0; … ; 15.209444148889675 0.39577317022402086 … 1.0 0.0; 0.0 0.0 … -3.0889000021489204 1.0], [0.054910881633198905 0.02025913121896805 … 0.6838641259466856 0.809700851562404; 0.0 0.8506970735473804 … -1.1337227773796799 -1.9511837272862618; … ; 0.0 0.0 … -79.32413552050515 -50.16481433996946; 0.39177317509945886 0.14632848706835955 … 0.0 -47.68112934439564])

In [103]:
@time block_LU(A3)

 15.385267 seconds (4.00 M allocations: 20.634 GiB, 38.40% gc time)


([1.0 0.0 … 0.0 0.0; 3.0965922842084077 1.0 … 0.0 0.0; … ; 15.20944414874223 0.39577317022226405 … 1.0 0.0; 7.134709249677594 0.00209883897407292 … -5.269290399185727 1.0], [0.054910881633198905 0.02025913121896805 … 0.6838641259466856 0.809700851562404; 0.0 0.8506970735473804 … -1.1337227773796799 -1.9511837272862615; … ; 0.0 0.0 … 3.967360082211501 5.929271419913377; 0.0 0.0 … 0.0 24.413557853668813])

In [104]:
@time pseudo_parallel_LU_block_LU(A3)

  5.500196 seconds (5.04 M allocations: 10.720 GiB, 16.27% gc time)


([1.0 0.0 … 0.0 0.0; 3.0965922842084077 1.0 … 0.0 0.0; … ; -19.62939864104914 -3.7750364653245403 … 1.0 0.0; 31.65464250079439 3.51842662767697 … 0.36934231528069605 1.0], [0.054910881633198905 0.02025913121896805 … 0.6838641259466856 0.809700851562404; 0.0 0.8506970735473804 … -1.1337227773796799 -1.9511837272862615; … ; 0.0 0.0 … -83.46921423455646 61.29024519686027; 0.0 0.0 … 0.0 8.712907272404756])

In [105]:
A2 = rand(4096,4096)

4096×4096 Matrix{Float64}:
 0.0296867  0.0950193  0.446196   …  0.249777   0.307937    0.747337
 0.114082   0.16329    0.17419       0.440044   0.421668    0.759555
 0.973958   0.197145   0.154852      0.590097   0.00850266  0.883437
 0.389139   0.313659   0.0889511     0.318088   0.634308    0.018493
 0.253464   0.870436   0.874104      0.645054   0.815052    0.735412
 0.737576   0.0393733  0.862329   …  0.922918   0.345616    0.826692
 0.686894   0.0998984  0.149798      0.590153   0.830671    0.261188
 0.672854   0.228385   0.0100861     0.684087   0.123277    0.653609
 0.212338   0.82499    0.131326      0.0707359  0.365844    0.0832599
 0.441277   0.729894   0.948379      0.919134   0.267154    0.545103
 0.223587   0.141336   0.204631   …  0.833694   0.891934    0.0823051
 0.700929   0.314508   0.461097      0.679484   0.841496    0.811495
 0.629377   0.497909   0.752857      0.307292   0.761614    0.340696
 ⋮                                ⋱                         ⋮
 0.707018   

In [110]:
@time LU(A2)

1238.513556 seconds (58.71 M allocations: 685.911 GiB, 3.34% gc time)


([1.0 0.0 … 0.0 0.0; 3.842847284695305 1.0 … 0.0 0.0; … ; 23.097172596194024 9.449922040015881 … 1.0 0.0; 24.9830135166097 7.804756308297792 … -0.20210243609981285 1.0], [0.029686712457045905 0.09501928952400829 … 0.30793705086947887 0.7473365855671892; 0.0 -0.20185421985590496 … -0.7616874784991267 -2.112345302372907; … ; 0.0 0.0 … -39.01874088286546 14.333403505755157; 0.0 0.0 … 0.0 20.02316683760623])

In [111]:
@time parallel_LU(A2)

636.156260 seconds (54.87 M allocations: 345.653 GiB, 43.13% gc time)


([1.0 0.0 … 0.0 0.0; 3.842847284695305 1.0 … 0.0 0.0; … ; 23.097172596194024 9.449922040015881 … 1.0 0.0; 0.0 0.0 … 0.9198529122592702 1.0], [0.029686712457045905 0.09501928952400829 … 0.30793705086947887 0.7473365855671892; 0.0 -0.20185421985590496 … -0.7616874784991267 -2.112345302372907; … ; 0.0 0.0 … 85.36761665097292 -110.98361947853168; 0.7416635385780833 0.7984451987400459 … 0.0 -17.721876429933218])

In [106]:
@time block_LU(A2)

166.100383 seconds (16.77 M allocations: 173.906 GiB, 7.36% gc time)


([1.0 0.0 … 0.0 0.0; 3.842847284695305 1.0 … 0.0 0.0; … ; 23.097172592099238 9.449922038146914 … 1.0 0.0; 24.983013504816952 7.804756302440132 … -0.20210243017316412 1.0], [0.029686712457045905 0.09501928952400829 … 0.30793705086947887 0.7473365855671892; 0.0 -0.20185421985590496 … -0.7616874784991267 -2.112345302372907; … ; 0.0 0.0 … -39.018739970251346 14.33340296885359; 0.0 0.0 … -8.881784197001252e-16 20.02316668829928])

In [107]:
@time pseudo_parallel_LU_block_LU(A2)

 76.289873 seconds (21.19 M allocations: 88.647 GiB, 21.75% gc time)


([1.0 0.0 … 0.0 0.0; 3.842847284695305 1.0 … 0.0 0.0; … ; 818.963370573739 37.39543171241954 … 1.0 0.0; -450.28472635076247 -20.875320908926785 … 1.475748585787109 1.0], [0.029686712457045905 0.09501928952400829 … 0.30793705086947887 0.7473365855671892; 0.0 -0.20185421985590496 … -0.7616874784991267 -2.112345302372907; … ; 0.0 0.0 … -115.84960485625751 196.51790670981362; 0.0 0.0 … 77.51793865194651 -213.5523371883619])

In [5]:
# Trabajamos con la matriz A aleatoria de orden 4096 definida previamente
L, U = pseudo_parallel_LU_block_LU(A2)

([1.0 0.0 … 0.0 0.0; 0.24873496849292703 1.0 … 0.0 0.0; … ; -8.91709715334129 -12.464606627411785 … 1.0 0.0; -1.848266003868957 -3.8976563469118632 … -0.8134867399098984 1.0], [0.9749886829104764 0.8935188148175884 … 0.8466022479749088 0.3364897449968206; 0.0 0.3885563330314892 … 0.598434529602937 0.29014922503996354; … ; 0.0 0.0 … -4052.2365091379615 -7012.950644595873; 0.0 0.0 … -3211.977320295415 -5559.952399560551])

In [1]:
print(Threads.nthreads())

4